### ISSUE TITLE
Communication with main thread

### ISSUE THREAD

**Issue by themuzzz** [vrtdev/flutter_workmanager#13]
First of all, amazing plugin! Thanks for the great work.

I'm new to Flutter development and had some progress with using isolates and SendPort to communicate data between the isolate and main thread. Unfortunately I found out the hard way that isolates do not continue running when the app goes to the background and that's when I found your plugin.

However, I can't seem to figure out what would be the best method with communicating between the main thread (layout) and the background isolate. The situation would be contacting a server multiple times and sending a progress (0-100) to the main thread which shows a progress indicator. The user would be able to dismiss the progress view and check the progress later where it would continue the progress.
I solved this now with an isolate connected to a parent widget which keeps the SendPort connection always open. So if a child widget closes/changes that parent would still have the progress.

Any ideas how this would be possible in your plugin?

Thanks!

Themuzz

**Comment by timrijckaert** [comment]
Hi 👋, 

I think you are looking for something this plugin does not provide.
This plugin allows you to spawn a background Isolate, but does *not* communicate back with the main isolate, simply because it is not necessarily started. 

What you describe is something that is know in Android as a _[foreground service](https://developer.android.com/guide/components/services)_.
A _foreground service_ keeps your app awake while doing some background job.  

In your example this would mean uploading a _big_ file to a server and seeing its progress.  
Every _foreground service_ in Android requires a notification so the user knows what is going on.  
You could either provide a progress ui in your notification or open up a `MethodChannel` in your Android service to post the progress there and react on it in Flutter.  

<img width="360" alt="android_notifications12" src="https://user-images.githubusercontent.com/6739443/62408942-58412480-b5d0-11e9-9eb7-049f34594536.png">
