### ISSUE TITLE
 Type mismatch: inferred type is PluginRegistry? but FlutterEngine was expected

### ISSUE THREAD

**Issue by billyurs** [vrtdev/flutter_workmanager#130]
I have followed same instruction for platform setup, but my stacktrace looks like this:

> kt: (15, 48): Type mismatch: inferred type is PluginRegistry? but FlutterEngine was expected
> FAILURE: Build failed with an exception.                                
> What went wrong:                                                      
> Execution failed for task ':app:compileDebugKotlin'.                    
> Compilation error. See log for more details                           
> Try:                                                                  
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get > more log output. Run with --scan to get full insights.
> Get more help at https://help.gradle.org 

My Kotlin file is 

```kotlin
import be.tramckrijte.workmanager.WorkmanagerPlugin
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.GeneratedPluginRegistrant

class App : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        WorkmanagerPlugin.setPluginRegistrantCallback(this)
    }

    override fun registerWith(reg: PluginRegistry?) {
        GeneratedPluginRegistrant.registerWith(reg)
    }
}
```

**Comment by yase-hesham** [comment]
same problem

**Comment by mohamadlounnas** [comment]
same

**Comment by Muda-r** [comment]
Doesn't work with java too. This was also a problem before here but there is still no answer https://github.com/vrtdev/flutter_workmanager/issues/126
Any help would be appreciated

**Comment by timrijckaert** [comment]
Hey all sorry for the wait, 

We identified this is due to a breaking change in Flutter v12.0 in how Flutter plugins are registered with the new Android v2 embedding.
[See this blogpost for more info](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration)
and this one:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by timrijckaert** [comment]
A new version of `WorkManager` (0.2.0) is now available on pub.dev.
Could you guys try and see if it works?

Thanks in advance.

**Comment by Muda-r** [comment]
Thanks for the update! Everything works perfectly, except now I've got an exeption: `Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference, null)` It doesn't stop the app from working properly, is this something I should fix or do I ignore it?

**Comment by timrijckaert** [comment]
Can you post the complete stacktrace?
We don't use the `PackageManager` so I'm wondering if this is something `flutter_workmanager` related. 
Do you experience this too with the sample app?

**Comment by Muda-r** [comment]
This happens when I tried to turn on the example app:
`C:\Users\Jovan\Desktop\flutter_workmanager-master\example\android\app\src\main\AndroidManifest.xml:5:5-25:19 Error:
	tools:replace specified at line:5 for attribute android:name, but no new value specified
C:\Users\Jovan\Desktop\flutter_workmanager-master\example\android\app\src\main\AndroidManifest.xml Error:
	Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Finished with error: Gradle task assembleDebug failed with exit code 1
`
but when I started my app again to copy the stack, the error didn't appear. That was weird? Even with the error it worked so I guess it isn't a big deal. I'll report back if it happens again.

**Comment by Muda-r** [comment]
This happens when I tried to turn on the example app:
`C:\Users\Jovan\Desktop\flutter_workmanager-master\example\android\app\src\main\AndroidManifest.xml:5:5-25:19 Error:
	tools:replace specified at line:5 for attribute android:name, but no new value specified
C:\Users\Jovan\Desktop\flutter_workmanager-master\example\android\app\src\main\AndroidManifest.xml Error:
	Validation failed, exiting

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Finished with error: Gradle task assembleDebug failed with exit code 1
`
but when I started my app again to copy the stack, the error didn't appear. That was weird? Even with the error it worked so I guess it isn't a big deal. I'll report back if it happens again.
