### ISSUE TITLE
Question: Fetching when app is running + background

### ISSUE THREAD

**Issue by AAverin** [vrtdev/flutter_workmanager#147]
Hello.
I roughly understand how this would work for Android, but not so clear on iOS.
I want to this workmanager to download a big file from network.

If my users presses download button while the app is running on the screen, I would expect download to start instantly on both iOS and Android. If user in the middle of download decides to switch to another app, on Android I would expect notification to still stay active keeping background service active and showing download progress.
How would this work on iOS? I don't fully get these 15 minutes time limits.

What I need is to download big file and still let user switch apps and make sure download doesn't break.

Thanks

**Comment by petermnt** [comment]
Hello,

This is currently not supported by the plugin, and isn't really the use case of WorkManager.

For iOS the only thing that is supported is getting the chance to handle some background work if and when the system allows you. So you can't use this for specific user actions.

For Android WorkManager also isn't intended for this, because scheduling a Worker has no guarantee that it will get executed immediately. It is intended for background work.
This is the Android API relevant for your use case: https://developer.android.com/reference/android/app/DownloadManager - but this is outside of the scope of this plugin.

**Comment by AAverin** [comment]
WorkManager seems to have no issues with long running jobs that could be also downloading big files https://developer.android.com/topic/libraries/architecture/workmanager/advanced/long-running
Any chance to find some good solution for iOS world to have this as a feature for flutter too? Looks like there aren't good ways to have background downloads in Flutter now.

**Comment by petermnt** [comment]
@AAverin  You can have a look at https://github.com/fluttercommunity/flutter_downloader
