### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by FarmaanElahi** [vrtdev/flutter_workmanager#84]
Build failed with error 
```
'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'
``` in swift 4.2

**Comment by Kymer** [comment]
Which Xcode version are you using? I believe `UIImagePNGRepresentation` was used in Swift 4.0 and has been renamed to `pngData()` in 4.2. The documentation isn't clear on the API change though.

**Comment by FarmaanElahi** [comment]
I am using XCode 10

**Comment by Kymer** [comment]
Xcode 10.0 or 10.3? And can you double check the Swift version you have set for the iOS project? (you can find that under the _Build Settings_ tab of the _Runner_ target)

**Comment by FarmaanElahi** [comment]
Sure will try and let you know

**Comment by andreidiaconu** [comment]
I was getting the same error at build time. Turns out I was using Swift 4.0 and upgrading to 4.2 solved the problem for me. 

If anyone else lands on this page looking for a solution, you should probably check your Swift version in *Runner* -> *Build Settings* -> *Swift Language Version*.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/1402046/75268770-a03fc700-5800-11ea-9c7c-32574669cd03.png">

**Comment by andreidiaconu** [comment]
I was getting the same error at build time. Turns out I was using Swift 4.0 and upgrading to 4.2 solved the problem for me. 

If anyone else lands on this page looking for a solution, you should probably check your Swift version in *Runner* -> *Build Settings* -> *Swift Language Version*.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/1402046/75268770-a03fc700-5800-11ea-9c7c-32574669cd03.png">

**Comment by andreidiaconu** [comment]
I was getting the same error at build time. Turns out I was using Swift 4.0 and upgrading to 4.2 solved the problem for me. 

If anyone else lands on this page looking for a solution, you should probably check your Swift version in *Runner* -> *Build Settings* -> *Swift Language Version*.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/1402046/75268770-a03fc700-5800-11ea-9c7c-32574669cd03.png">

**Comment by andreidiaconu** [comment]
I was getting the same error at build time. Turns out I was using Swift 4.0 and upgrading to 4.2 solved the problem for me. 

If anyone else lands on this page looking for a solution, you should probably check your Swift version in *Runner* -> *Build Settings* -> *Swift Language Version*.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/1402046/75268770-a03fc700-5800-11ea-9c7c-32574669cd03.png">
